//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VineExpert_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class White
    {
        public int ID { get; set; }
        public float FixedAcidity { get; set; }
        public float VolatileAcidity { get; set; }
        public decimal CitricAcid { get; set; }
        public float ResidualSugar { get; set; }
        public float Chlorides { get; set; }
        public float FreeSulfurDioxide { get; set; }
        public float TotalSulfurDioxide { get; set; }
        public float Density { get; set; }
        public float PH { get; set; }
        public float Sulphates { get; set; }
        public float Alcohol { get; set; }
        public float Quality { get; set; }
        public int IsTest { get; set; }
    }
}
